### ISSUE TITLE
Expand paths in filter_files

### ISSUE THREAD

**Issue by mknapik** [seattlerb/path_expander#2]
Issue copied from seattlerb/flay#58

`flayignore` does not respect globs if files are passed as absolute paths (related to https://github.com/mmozuras/pronto-flay/issues/10).

To reproduce the error:

```
git clone https://github.com/mknapik/pronto-flay-ignore-issue
cd pronto-flay-ignore-issue
flay `pwd`/.
flay .
```

`flay .` works as expected. `flay $PWD/.` ignores values in `.flayignore`.

**Comment by zenspider** [comment]
Done w/ mods. thanks!
